spring:
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
          stateless: true
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectedTimeout: 1000
        readTimeout: 1000